bundler_args: --clean --deployment
sudo: false
cache: bundler
language: ruby
gemfile:
  - Gemfile
  - gemfiles/Gemfile-3.2
  - gemfiles/Gemfile-4.0
  - gemfiles/Gemfile-4.1
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
before_script:
  "cd spec/dummy && BUNDLE_GEMFILE=../../$BUNDLE_GEMFILE bundle exec rake db:create && BUNDLE_GEMFILE=../../$BUNDLE_GEMFILE bundle exec rake db:migrate"